export const BioData = [
    {
        id: 1,
        name: 'The Batman',
        job: ['Action', 'Suspense', 'Crime', 'Drama', 'Thriller'],
        description: 'Batman, also known as the Dark Knight, is a superhero who first appeared in Detective Comics #27 in 1939. Created by artist Bob Kane and writer Bill Finger, Batman quickly became one of the most popular and enduring characters in comic book historBatman is the alter ego of Bruce Wayne, a billionaire industrialist and philanthropist who witnessed the murder of his parents as a child. Driven by a desire for justice and a hatred of crime, Bruce dedicated his life to becoming a master detective and crime-fighter.Unlike many other superheroes, Batman has no superhuman powers. Instead, he relies on his intellect, physical prowess, and an arsenal of high-tech gadgets and weapons to battle the criminal underworld of Gotham City. Batman is known for his iconic costume, featuring a black cowl with pointed ears, a flowing cape, and a bat symbol emblazoned on his chest.Batmans rogues gallery of villains includes some of the most iconic characters in comic book history, including the Joker, the Penguin, and Catwoman. He also frequently collaborates with other superheroes, including Superman and the Justice League.Throughout his many appearances in comics, TV shows, movies, and other media, Batman has remained a popular and beloved character. He is known for his brooding, enigmatic personality, as well as his unwavering dedication to justice and his iconic symbol of the bat, which strikes fear into the hearts of criminals everywhere.Beyond his superhero persona, Batman is also a complex and nuanced character, grappling with the trauma of his past and the ethical implications of his vigilantism. He is a symbol of hope and justice for many, and remains one of the most enduring and iconic characters in all of popular culture.',
        authorName: 'Matt Reevesoe',
        authorAvatar: 'author.jpg',
        createdAt: 'June 03, 2021',
        cover: "g1.jpg",
    },
    {
        id: 2,
        name: 'Man of Steel ',
        job: ['Action', 'Adventure'],
        description: "Superman, also known as the Man of Steel, is a superhero who first appeared in Action Comics #1 in 1938. Created by writer Jerry Siegel and artist Joe Shuster, Superman quickly became one of the most popular and recognizable characters in American pop culture.Superman is the alter ego of Clark Kent, a reporter for the Daily Planet newspaper in the fictional city of Metropolis. Born on the planet Krypton, Superman was sent to Earth as an infant by his parents, who foresaw the imminent destruction of their planet. Raised by the Kents, a farming family in Smallville, Kansas, Clark grew up to discover that he possessed incredible superhuman powers, including super strength, flight, and the ability to shoot heat rays from his eyes. As Superman, Clark uses his powers to fight for truth, justice, and the American way. He battles a variety of supervillains and other threats, both on Earth and beyond, including the evil genius Lex Luthor and the powerful alien General Zod. Superman is known for his iconic blue and red costume, featuring a stylized S emblem on his chest. He also wears a red cape, which he uses to fly through the air. In addition to his physical powers, Superman is also incredibly intelligent and possesses a strong moral compass.Over the years, Superman has appeared in countless comics, TV shows, movies, and other forms of media. He has inspired generations of fans with his bravery, selflessness, and commitment to doing what is right. Today, Superman remains one of the most beloved and enduring characters in all of superhero fiction, a symbol of hope and heroism that continues to inspire people of all ages.",
        authorName: 'Zack Snyder',
        authorAvatar: 'author.jpg',
        createdAt: 'June 14, 2014',
        cover: "g2.jpg",
    },
    {
        id: 3,
        name: 'Joker ',
        job: ['Crime', 'Drama', 'Thriller'],
        description: 'The Joker is one of the most iconic and complex villains in comic book history. He first appeared in Batman #1 in 1940, created by artist Bob Kane, writer Bill Finger, and Jerry Robinson. The Joker has since become a staple of Batman stories, appearing in countless comics, movies, and other forms of mediThe Jokers origin story is shrouded in mystery and has been told in various ways over the years.One of the most common interpretations is that he was once a failed stand- up comedian who fell into a vat of chemicals during a robbery gone wrong, transforming him into the madman known as the Joker.He is known for his pale skin, green hair, and maniacal laughter.The Joker is a violent and unpredictable criminal, known for his twisted sense of humor and penchant for chaos.He is Batmans arch- nemesis, constantly testing the Dark Knights morality and sanity.The Joker has committed countless heinous crimes over the years, including the murder of Jason Todd, the second Robin, and the crippling of Barbara Gordon, aka Batgirl.Despite his monstrous acts, the Joker remains a fascinating and compelling character, with many interpretations offering different perspectives on his motivations and psyche.Some portray him as a nihilistic anarchist who seeks to destroy society and Batmans moral code, while others depict him as a tragic figure, driven to madness by a cruel and unjust world.The Jokers legacy extends far beyond comics and into popular culture, with iconic portrayals in movies, TV shows, and video games.Actors such as Jack Nicholson, Heath Ledger, and Joaquin Phoenix have brought the Joker to life on the big screen, each offering a unique interpretation of the character.The Joker remains one of the most enduring and popular villains in all of fiction, a testament to the enduring power of Batmans rogues gallery and the complexity of the human psyche.',
        authorName: 'Todd Phillips',
        authorAvatar: 'author.jpg',
        createdAt: 'October 04, 2019',
        cover: "g3.jpg",
    },
    {
        id: 4,
        name: 'Aquaman ',
        job: ['Action', 'Adventure', 'Fanstasy'],
        description: 'Aquaman, also known as Arthur Curry, is the ruler of the underwater kingdom of Atlantis. He possesses superhuman strength, endurance, and durability, as well as the ability to communicate with sea creatures and swim at incredible speeds. Aquaman is known for his iconic orange and green costume, which features a trident and a golden bel Aquamans powers and abilities make him a formidable warrior both on land and underwater, and he has played a key role in many of the DC Universes most epic battles. He has also been a member of the Justice League, working alongside other heroes such as Superman, Batman, and Wonder Woman to protect the world from threats both terrestrial and extraterrestrial.In addition to his superhero duties, Aquaman is also a complex and nuanced character. He is torn between his duty to Atlantis and his love for the surface world, and struggles with the political and environmental challenges that come with being a ruler. He is also a family man, with a wife and son who factor heavily into his decisions and motivations.Over the years, Aquaman has appeared in numerous comic book series, TV shows, movies, and other forms of media. He is known for his unique set of powers and his iconic costume, as well as his status as one of the most recognizable and beloved characters in the DC Universe.',
        authorName: 'James Wan',
        authorAvatar: 'author.jpg',
        createdAt: 'December 21, 2018',
        cover: "g4.jpg",
    },
    {
        id: 5,
        name: 'SpiderMan ',
        job: ['Action', 'Suspense', 'Comdey', 'Thriller'],
        description: 'Spider-Man, also known as Peter Parker, is a superhero who was born and raised in New York City. Peters parents were killed when he was young, leaving him to be raised by his Uncle Ben and Aunt May.He attended high school at Midtown High School and was known for his intelligence and love for science.One day, while on a school field trip to a science exhibition, Peter was bitten by a radioactive spider. The spider bite gave him incredible superhuman abilities, including the ability to cling to surfaces, superhuman strength, and agility. After his uncle was tragically killed by a robber whom Peter could have stopped, Peter realized that with great power comes great responsibility and decided to use his powers to fight crime and protect the people of New York City.             Peter designed his own costume and adopted the moniker "Spider-Man." He has since become a beloved hero in the Marvel Universe, known for his quick wit, acrobatic fighting style, and spider- sense, which allows him to sense danger before it happens.Over the years, he has faced numerous villains, including his arch - nemesis the Green Goblin, and has worked alongside other heroes like the Avengers and the Fantastic Four. Despite the dangers he faces, Spider - Man remains committed to protecting the people of New York City and upholding the ideals of justice and responsibility.He continues to inspire people around the world with his bravery and selflessness, and has become an enduring icon of the superhero genre.',
        authorName: 'John Doe',
        authorAvatar: 'author.jpg',
        createdAt: 'June 03, 2021',
        cover: "g5.jpg",
    }
]